<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorProfileSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('vendor_profiles')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $now = now();

        DB::table('vendor_profiles')->insert([
            // Demo vendors (incomplete onboarding — no category set)
            ['id' => 2,  'user_id' => 4,  'category_id' => null, 'business_name' => 'Aphrodite Events',             'business_description' => 'Full-service wedding venue and catering specialists in Larnaca.',           'contact_first_name' => 'Eleni',    'contact_last_name' => 'Papadopoulos', 'location' => 'Larnaca, Cyprus',    'country' => null,     'city' => null,        'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3,  'user_id' => 5,  'category_id' => null, 'business_name' => 'Island Lens Studios',           'business_description' => 'Award-winning photography and live music for Cyprus weddings.',            'contact_first_name' => 'Andreas',  'contact_last_name' => 'Constantinou', 'location' => 'Paphos, Cyprus',     'country' => null,     'city' => null,        'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4,  'user_id' => 6,  'category_id' => null, 'business_name' => 'Bridal Atelier Cyprus',         'business_description' => "Limassol's premier destination for bridal gowns, bridesmaid dresses, and beauty.", 'contact_first_name' => 'Sofia', 'contact_last_name' => 'Nikkola',   'location' => 'Limassol, Cyprus',   'country' => null,     'city' => null,        'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5,  'user_id' => 7,  'category_id' => null, 'business_name' => 'Blue Mediterranean Experiences','business_description' => 'Luxury sea experiences — yacht hire, stag dos, and hen parties across Cyprus.',  'contact_first_name' => 'Nikos',    'contact_last_name' => 'Georgiou',     'location' => 'Ayia Napa, Cyprus',  'country' => null,     'city' => null,        'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6,  'user_id' => 8,  'category_id' => null, 'business_name' => 'Nicosia Flowers & Cars',        'business_description' => 'Floral artistry and vintage car hire for Nicosia weddings.',                'contact_first_name' => 'Maria',    'contact_last_name' => 'Loizidou',     'location' => 'Nicosia, Cyprus',    'country' => null,     'city' => null,        'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 0, 'created_at' => $now, 'updated_at' => $now],

            // Test vendor profiles (created via UI)
            ['id' => 7,  'user_id' => 19, 'category_id' => 13,   'business_name' => 'Test Wedding Photography',      'business_description' => 'Professional wedding photography in Cyprus',                             'contact_first_name' => 'Vendor',   'contact_last_name' => 'Test',         'location' => null,                 'country' => 'Cyprus', 'city' => 'Ayia Napa', 'phone' => '+357 96 123456',  'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8,  'user_id' => 21, 'category_id' => 3,    'business_name' => 'The flower',                    'business_description' => 'this is the description',                                               'contact_first_name' => 'Flower',   'contact_last_name' => 'test',         'location' => null,                 'country' => 'Cyprus', 'city' => 'Troodos',   'phone' => '+357',            'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9,  'user_id' => 22, 'category_id' => 1,    'business_name' => 'Aphrodite Grand Hall',          'business_description' => 'Stunning waterfront event spaces across Cyprus for your perfect wedding day.','contact_first_name' => 'Venue',   'contact_last_name' => 'test',         'location' => null,                 'country' => 'Cyprus', 'city' => 'Limassol',  'phone' => '+357 11111111',   'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'user_id' => 24, 'category_id' => 2,    'business_name' => 'Olive & Thyme Catering',        'business_description' => 'Award-winning Mediterranean cuisine crafted fresh for your special occasion.','contact_first_name' => 'Catering','contact_last_name' => 'Test',         'location' => null,                 'country' => 'Cyprus', 'city' => 'Nicosia',   'phone' => '+357 1111111',    'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'user_id' => 25, 'category_id' => 4,    'business_name' => 'The CarHire',                   'business_description' => 'This is the description',                                               'contact_first_name' => 'CarHire',  'contact_last_name' => 'test',         'location' => null,                 'country' => 'Cyprus', 'city' => 'Troodos',   'phone' => '+357',            'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'user_id' => 26, 'category_id' => 5,    'business_name' => 'the Photography',               'business_description' => 'This is the description',                                               'contact_first_name' => 'Photography','contact_last_name' => 'test',        'location' => null,                 'country' => 'Cyprus', 'city' => 'Troodos',   'phone' => '+357',            'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'user_id' => 27, 'category_id' => 6,    'business_name' => 'the Music',                     'business_description' => 'This is the description',                                               'contact_first_name' => 'Music',    'contact_last_name' => 'Test',         'location' => null,                 'country' => 'Cyprus', 'city' => 'Troodos',   'phone' => '+357',            'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 14, 'user_id' => 28, 'category_id' => 7,    'business_name' => 'The Bride Dress',               'business_description' => 'This is the description',                                               'contact_first_name' => 'BrideDress','contact_last_name' => 'test',        'location' => null,                 'country' => 'Cyprus', 'city' => 'Protaras',  'phone' => '+357',            'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 30, 'user_id' => 29, 'category_id' => 8,    'business_name' => 'The GroomSuite',                'business_description' => 'This is the description.',                                              'contact_first_name' => 'GroomSuite','contact_last_name' => 'test',        'location' => null,                 'country' => 'Cyprus', 'city' => 'Troodos',   'phone' => '+357',            'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],

            // Extra vendor demo profiles (fully onboarded)
            ['id' => 15, 'user_id' => 30, 'category_id' => 3,    'business_name' => 'Bloom & Petal Floristry',       'business_description' => 'Bespoke floral arrangements that transform every space into pure romance.',  'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Limassol',  'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'user_id' => 31, 'category_id' => 4,    'business_name' => 'Cyprus Classic Cars',           'business_description' => 'Iconic vintage and luxury cars to make your wedding arrival unforgettable.', 'contact_first_name' => null,      'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Larnaca',   'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'user_id' => 32, 'category_id' => 5,    'business_name' => 'Golden Hour Photography',       'business_description' => 'Capturing timeless moments with a cinematic, natural-light approach.',      'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Paphos',    'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 18, 'user_id' => 33, 'category_id' => 6,    'business_name' => 'Strings & Beats Music',         'business_description' => 'Live bands and DJs for ceremony, cocktail hour and reception dancing.',       'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Nicosia',   'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 19, 'user_id' => 34, 'category_id' => 7,    'business_name' => 'La Maison Bridal',              'business_description' => 'Exclusive bridal gowns — rent or buy — with full alteration service.',        'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Limassol',  'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 20, 'user_id' => 35, 'category_id' => 8,    'business_name' => 'The Dapper Groom',              'business_description' => 'Tailored groom suits for rent or purchase, fitted by expert stylists.',       'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Nicosia',   'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 21, 'user_id' => 36, 'category_id' => 9,    'business_name' => 'Blush & Ivory Bridesmaids',     'business_description' => 'Beautiful bridesmaid dresses in every size, colour and style imaginable.',    'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Limassol',  'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 22, 'user_id' => 37, 'category_id' => 10,   'business_name' => 'Savile Row Cyprus',             'business_description' => 'Sharp suits for the best man and groomsmen, perfectly coordinated.',          'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Larnaca',   'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 23, 'user_id' => 38, 'category_id' => 11,   'business_name' => 'Little Blooms Dresses',         'business_description' => 'Adorable flower girl dresses in a rainbow of colours and sizes.',             'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Paphos',    'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 24, 'user_id' => 39, 'category_id' => 12,   'business_name' => 'Azure Yacht Charters',          'business_description' => 'Luxury yacht charters for wedding parties around the Cyprus coastline.',      'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Limassol',  'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 25, 'user_id' => 40, 'category_id' => 13,   'business_name' => 'Stag King Cyprus',              'business_description' => 'Epic bachelor party experiences — boats, bars and beyond.',                   'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Ayia Napa', 'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 26, 'user_id' => 41, 'category_id' => 14,   'business_name' => 'Hen Party Queens',              'business_description' => 'Glamorous hen do packages tailored to the bride-to-be.',                     'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Protaras',  'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 27, 'user_id' => 42, 'category_id' => 15,   'business_name' => 'Elysium Boutique Hotel',        'business_description' => 'Boutique wedding accommodation for the couple and guests.',                   'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Paphos',    'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 28, 'user_id' => 43, 'category_id' => 16,   'business_name' => 'The Wedding Bar Co.',           'business_description' => 'Premium mobile bar hire with expert mixologists and full setup.',              'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Limassol',  'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 29, 'user_id' => 44, 'category_id' => 17,   'business_name' => 'Glow Bridal Beauty',            'business_description' => 'Professional bridal makeup and trials by award-winning artists.',              'contact_first_name' => null,       'contact_last_name' => null,           'location' => null,                 'country' => 'Cyprus', 'city' => 'Nicosia',   'phone' => null,              'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 31, 'user_id' => 46, 'category_id' => 18,   'business_name' => 'Silk & Shear Studio',           'business_description' => 'Luxury bridal hair styling studio specialising in updos, blowdrys, braids and extensions. Serving all of Cyprus.', 'contact_first_name' => 'Silk', 'contact_last_name' => 'Shear', 'location' => 'Limassol, Cyprus', 'country' => 'Cyprus', 'city' => 'Limassol', 'phone' => null, 'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 32, 'user_id' => 47, 'category_id' => 18,   'business_name' => 'The hair saloon',               'business_description' => 'this is the description',                                                   'contact_first_name' => 'Hamza',    'contact_last_name' => 'Saeed',        'location' => null,                 'country' => 'Cyprus', 'city' => 'Protaras',  'phone' => '+357 124122151',  'avatar_url' => null, 'onboarding_completed' => 1, 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}
